# Generated by Django 5.1.6 on 2025-03-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add', 'Can add a new book'), ('can_create', 'Can create a new book'), ('can_edit', 'Can edit an existing book'), ('can_delete', 'Can remove a book')]},
        ),
    ]
