# Generated by Django 5.1.6 on 2025-03-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view a book'), ('can_create', 'Can create a book'), ('can_edit', 'Can edit an existing book'), ('can_delete', 'Can delete a book')]},
        ),
    ]
